project:
  type: website
  output-dir: docs
  
website:
  title: "The Confluence Projects"
  google-analytics: "G-X7TVYB1MH3"
  description: "Investigating the confluence of health risk"
  favicon: "img/confluence3.jpg"
  site-url: https://www.confluence-project.org
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: rn.qmd
        text: News & Posts
      - text: Resources
        menu:
        - gridex.qmd
        - data.qmd
      - href: team.qmd
        text: Team
    right:
      - icon: rss
        href: rn.xml
  search: true
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: "Helvetica Neue"
    fontsize: 1.1em

editor: visual

