project:
  type: website
  output-dir: docs
  
website:
  title: "The Confluence Projects"
  google-analytics: "G-X7TVYB1MH3"
  description: "Investigating the confluence of health risk"
  favicon: "img/confluence2.png"
  site-url: http://www.confluence-project.org
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: rn.qmd
        text: News & Posts
      - href: data.qmd
        text: Resources
      - href: team.qmd
        text: Team
    right:
      - icon: rss
        href: rn.xml
  search: true
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: "Helvetica Neue"
    fontsize: 1.1em

editor: visual

